name: GitHub Actions Demo
on: [push]
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Sequelize Install
        run: npm install sequelize
      - name: Sequelize sqlite
        run: npm install sqlite3
      - name: Sequelize sqlite
        run: npm install sequelize-cli
      - name: Create empty project
        run: npx sequelize-cli init      